name: dart_grpc_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grpc:
  protobuf:


  cupertino_icons:


dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true